/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xerox_jatanor_JAtanor */

#ifndef _Included_com_xerox_jatanor_JAtanor
#define _Included_com_xerox_jatanor_JAtanor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xerox_jatanor_JAtanor
 * Method:    LoadProgramImplementation
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_xerox_jatanor_JAtanor_LoadProgramImplementation
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_xerox_jatanor_JAtanor
 * Method:    ExecuteFunctionImplementation
 * Signature: (ILjava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xerox_jatanor_JAtanor_ExecuteFunctionImplementation
  (JNIEnv *, jobject, jint, jstring, jobjectArray);

/*
 * Class:     com_xerox_jatanor_JAtanor
 * Method:    ExecuteFunctionArrayImplementation
 * Signature: (ILjava/lang/String;[Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_xerox_jatanor_JAtanor_ExecuteFunctionArrayImplementation
  (JNIEnv *, jobject, jint, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
